config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'texts/edit'
  end

  namespace :admin do
    get 'texts/update'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, :defaults => {:format => :json}  do
    resource :calendar, only: [:show] do
      collection do
        get 'old'
      end
    end
    resources :teams, only:[:index] do
      collection do
        get 'by_points'
        get 'by_group'
      end
    end
    resources :articles, only: [:index]

    resource :leaderboard, only: [:show]

    resource :options, only:[:show]

    resource :texts, only: [:show]

    resource :menu, only:[:show]

    resources :matches, only: [] do
      collection do
        get 'upcoming'
      end
    end
  end

  namespace :admin do
    resources :teams
    resources :players
    resources :matches
    resources :journeys
    resources :articles do
      member do
        post :move
      end
    end
    resource :calendar, only:[:edit,:update]
    resource :options, only:[:edit,:update]
    resource :texts, only:[:edit,:update]
    resources :groups
    resource :menu, only:[:edit,:update]
  end

  resource :session, only:[:create,:new,:destroy]

  root to: 'sessions#new'
end

app/models/article.rb
class Article < ApplicationRecord
  acts_as_sortable
  validates :url, presence: true
  validates :title, presence: true
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_filter :authorize
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.ordered_by_position_asc
  end

  def move
    @article = Article.find(params[:id])
    @article.move_to! params[:position]
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to edit_admin_article_path (@article.id), notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to edit_admin_article_path (@article.id), notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to admin_articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.fetch(:article, {}).permit(:url,:is_youtube,:thumb_url,:title,:subtitle,:date,:thumb_url)
    end
end

app/controllers/api/articles_controller.rb
class API::ArticlesController < ApplicationController
  def index
    @articles = Article.order(:position).last(3)
    render json: @articles, :callback  => params[:callback]
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/api/articles_helper.rb
module API::ArticlesHelper
end

app/views/admin/articles/_article.html.erb
<!-- app/views/things/_thing.html.erb -->

<!-- required attributes are data-role, data-move-url, data-position -->
<li data-role="thing<%= @article.id %>" data-move-url="<%= move_admin_article_path(@article) %>" data-position="<%= @article.position %>">
  <h2><%= @article.id %></h2>
</li>

<%= link_to 'Edit', edit_admin_article_path(@article.id) %></td>
<%= link_to 'Destroy', admin_article_path(@article.id), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/admin/articles/_form.html.erb
<%= form_for [:admin,@article] do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.label :url %>
    <%= f.text_field :url %>

    <%= f.label :is_youtube %>
    <%= f.check_box :is_youtube %>

    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>

    <%= f.label :date %>
    <%= f.date_select :date %>

    <%= f.label :thumb_url %>
    <%= f.text_field :thumb_url %>

    <%= f.submit %>
  </div>
<% end %>

app/views/admin/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', admin_article_path(@article.id) %> |
<%= link_to 'Back', admin_articles_path %>

app/views/admin/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>


<ol data-role="activerecord_sortable" class="sortable">
  <% @articles.each do |article| %>
      <li data-role="articles<%= article.id %>" data-move-url="<%= move_admin_article_url(article.id) %>" data-position="<%= article.position %>">
        <span> <%= article.title %></span>

      <%= link_to 'Edit', edit_admin_article_path(article.id) %></td>
      <%= link_to 'Destroy', admin_article_path(article.id), method: :delete, data: { confirm: 'Are you sure?' } %>
      </li>
  <% end %>

</ol>

<br>

<%= link_to 'New Article', new_admin_article_path %>

app/views/admin/articles/move.js.erb
// app/views/things/move.js.erb

var node = $('*[data-role="thing<%= @article.id %>"]');
var new_node_html = '<%= j render @article %>';

node.replaceWith(new_node_html);

app/views/admin/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', admin_articles_path %>

app/views/admin/articles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_article_path(@article) %> |
<%= link_to 'Back', admin_articles_path %>