config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'texts/edit'
  end

  namespace :admin do
    get 'texts/update'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, :defaults => {:format => :json}  do
    resource :calendar, only: [:show] do
      collection do
        get 'old'
      end
    end
    resources :teams, only:[:index] do
      collection do
        get 'by_points'
        get 'by_group'
      end
    end
    resources :articles, only: [:index]

    resource :leaderboard, only: [:show]

    resource :options, only:[:show]

    resource :texts, only: [:show]

    resource :menu, only:[:show]

    resources :matches, only: [] do
      collection do
        get 'upcoming'
      end
    end
  end

  namespace :admin do
    resources :teams
    resources :players
    resources :matches
    resources :journeys
    resources :articles do
      member do
        post :move
      end
    end
    resource :calendar, only:[:edit,:update]
    resource :options, only:[:edit,:update]
    resource :texts, only:[:edit,:update]
    resources :groups
    resource :menu, only:[:edit,:update]
  end

  resource :session, only:[:create,:new,:destroy]

  root to: 'sessions#new'
end

app/models/match.rb
class Match < ApplicationRecord

  validates :team_a_id, presence: true
  validates :team_b_id, presence: true

  belongs_to :a_team, class_name: 'Team', foreign_key: 'team_a_id'
  belongs_to :b_team, class_name: 'Team', foreign_key: 'team_b_id'
  belongs_to :journey

  def teams
    [a_team, b_team]
  end

end

app/controllers/admin/matches_controller.rb
class Admin::MatchesController < ApplicationController
  before_filter :authorize
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.order(:time)
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to edit_admin_match_path(@match.id), notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to edit_admin_match_path(@match.id), notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to admin_matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.fetch(:match, {}).permit(:team_a_id,:score_a,:team_b_id,:score_b,:time,:journey_id)
    end
end

app/controllers/api/matches_controller.rb
class API::MatchesController < ApplicationController
  def upcoming
    @matches = Match.order(:time).where('time > ?', DateTime.now).select(:score_a,:score_b,:team_a_id,:team_b_id,:time).limit(6)

    render json: @matches, include: { teams: { only: [:name,:logo_url]} }, :callback  => params[:callback]
  end
end

app/helpers/admin/matches_helper.rb
module Admin::MatchesHelper
end

app/helpers/api/matches_helper.rb
module API::MatchesHelper
end

app/views/admin/matches/_form.html.erb
<%= form_for [:admin,@match] do |f| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">

    <%= f.label :team_a_id %>
    <%= f.collection_select :team_a_id, Team.all, :id, :name, {:selected => @match.a_team.try(:id).to_s} %>

    <%= f.label :score_a %>
    <%= f.text_field :score_a %>

    <%= f.label :team_b_id %>
    <%= f.collection_select :team_b_id, Team.all, :id, :name, {:selected => @match.b_team.try(:id).to_s} %>

    <%= f.label :score_b %>
    <%= f.text_field :score_b %>

    <%= f.label :time %>
    <%= f.datetime_select :time ,{start_year:2016,end_year:2017} %>
    <%= f.label :journey_id %>
    <%= f.collection_select :journey_id, Journey.all, :id, :name, {:selected => @match.journey_id.to_s} %>

    <%= f.submit %>

  </div>
<% end %>

app/views/admin/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Show', admin_match_path(@match.id) %> |
<%= link_to 'Back', admin_matches_path %>

app/views/admin/matches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Matches</h1>

<table>
  <thead>
    <tr>
      <th>Team a</th>
      <th>Team b</th>
      <th>Date</th>
      <th>Journey</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <!--<td><%= link_to 'Show', admin_match_path(match.id) %></td>-->
        <td><%= match.a_team.try(:name) %> </td>
        <td> <%= match.b_team.try(:name) %> </td>
        <td> <%= match.time.strftime('%c') %> </td>
        <td> <%= match.journey.try(:name) %> </td>
        <td><%= link_to 'Edit', edit_admin_match_path(match.id) %></td>
        <td><%= link_to 'Destroy', admin_match_path(match.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match', new_admin_match_path %>

app/views/admin/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Back', admin_matches_path %>

app/views/admin/matches/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_match_path(@match) %> |
<%= link_to 'Back', admin_matches_path %>