config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'texts/edit'
  end

  namespace :admin do
    get 'texts/update'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, :defaults => {:format => :json}  do
    resource :calendar, only: [:show] do
      collection do
        get 'old'
      end
    end
    resources :teams, only:[:index] do
      collection do
        get 'by_points'
        get 'by_group'
      end
    end
    resources :articles, only: [:index]

    resource :leaderboard, only: [:show]

    resource :options, only:[:show]

    resource :texts, only: [:show]

    resource :menu, only:[:show]

    resources :matches, only: [] do
      collection do
        get 'upcoming'
      end
    end
  end

  namespace :admin do
    resources :teams
    resources :players
    resources :matches
    resources :journeys
    resources :articles do
      member do
        post :move
      end
    end
    resource :calendar, only:[:edit,:update]
    resource :options, only:[:edit,:update]
    resource :texts, only:[:edit,:update]
    resources :groups
    resource :menu, only:[:edit,:update]
  end

  resource :session, only:[:create,:new,:destroy]

  root to: 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  acts_as_sortable
  validates :url, presence: true
  validates :title, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  validates_presence_of :name
  validates_uniqueness_of :name, {case_sensitive: true}

  has_many :teams, dependent:  :nullify

  def ordered_teams
    self.teams.select(:name,:victories,:defeats,:points,:logo_url,:short_name).order(:points => :desc )
  end
end

app/models/journey.rb
class Journey < ApplicationRecord

  @@counter = 0
  validates :name, presence: true

  has_many :matches, -> { order(:time) },dependent: :destroy

  def by_group
    self.matches
  end

  def test
    groups = []
    self.matches.each{|match|groups << match.a_team.group.name}
    groups.each {}
  end

  def counter_journey
    @@counter = @@counter +1
  end


end

app/models/match.rb
class Match < ApplicationRecord

  validates :team_a_id, presence: true
  validates :team_b_id, presence: true

  belongs_to :a_team, class_name: 'Team', foreign_key: 'team_a_id'
  belongs_to :b_team, class_name: 'Team', foreign_key: 'team_b_id'
  belongs_to :journey

  def teams
    [a_team, b_team]
  end

end

app/models/menu.rb
class Menu < ApplicationRecord
end

app/models/option.rb
class Option < ApplicationRecord

  has_secure_password
  
  validates :facebook_url, presence: true
  validates :twitter_url, presence: true
  validates :instagram_url, presence: true
  validates :youtube_url, presence: true
  validates :mas_noticias_url, presence: true
end

app/models/player.rb
class Player < ApplicationRecord

  validates :name, presence: true
  validates :position, presence: true


  belongs_to :team

  def order

  end
end

app/models/team.rb
class Team < ApplicationRecord

  validates :name, presence: true
  validates :victories, numericality: { only_integer: true }
  validates :defeats, numericality: { only_integer: true }
  validates :kills, numericality: { only_integer: true }
  validates :deaths, numericality: { only_integer: true }
  validates :points, numericality: { only_integer: true }

  has_many :players, -> { where(active: true) }, dependent: :nullify
  belongs_to :group


  def matches
    Match.where("team_a_id = ? OR team_b_id = ?", self.id, self.id)
  end

  def ordered_players
    query = "SELECT * FROM Players WHERE team_id= #{self.id} AND active = true  ORDER BY CASE
                    WHEN position='Superior' THEN  1
                    WHEN position='Jungla' THEN 2
                    WHEN position='Central' THEN 3
                    WHEN position='Tirador' THEN 4
                    WHEN position='Soporte' THEN 5
                ELSE 6
              END";
    results = ActiveRecord::Base.connection.execute(query)
  end

end

app/models/text.rb
class Text < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token, if: :json_request?

  # THIS
  before_action :set_headers

  def current_user
    @current_user ||= Option.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    unless current_user
      flash[:danger] = "Necesitas Logearte"
      redirect_to new_session_path
    end

  end

  def json_request?
    request.format.json?
  end

  # THIS
  def set_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
  end


  def pretty_journeys string
    if string =~ /\d/
      string  = string.gsub(/[^0-9]/, '')
    end

    return string
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @disable_nav = true
  end

  def create
    user = Option.find_by_username(params[:username])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      flash[:success]  = "Logeado!"
      redirect_to edit_admin_calendar_path
    else
    # If user's login doesn't work, send them back to the login form.
      flash[:danger]  = "Nombre de usuario o contraseña incorrecta"
      redirect_to new_session_path
    end

  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Bye bye"
    redirect_to new_session_path
  end


end

app/helpers/admin/menus_helper.rb
module Admin::MenusHelper
end

app/helpers/admin/teams_helper.rb
module Admin::TeamsHelper
end

app/helpers/admin/texts_helper.rb
module Admin::TextsHelper
end

app/helpers/api/menus_helper.rb
module API::MenusHelper
end

app/helpers/api/teams_helper.rb
module API::TeamsHelper
end

app/helpers/api/texts_helper.rb
module API::TextsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/shared/_menu.html.erb
<nav class="navbar navbar-default">
       <div class="container-fluid">
         <div class="navbar-header">
           <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
             <span class="sr-only">Toggle navigation</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </button>
           <a class="navbar-brand" href="#">Riot Panel</a>
         </div>
         <div id="navbar" class="navbar-collapse collapse navbar-right">
           <ul class="nav navbar-nav">
             <li><%= link_to 'Menu',edit_admin_menu_path %></li>
             <li><%= link_to 'Groups',admin_groups_path %></li>
             <li><%= link_to 'Teams',admin_teams_path %></li>
             <li><%= link_to 'Players',admin_players_path %></li>
             <li><%= link_to 'Matches',admin_matches_path %></li>
             <li><%= link_to 'Journeys',admin_journeys_path %></li>
             <li><%= link_to 'Articles',admin_articles_path %></li>
             <li><%= link_to 'Calendar',edit_admin_calendar_path %></li>
             <li><%= link_to 'Options', edit_admin_options_path %></li>
             <li><%= link_to 'Texts', edit_admin_texts_path %></li>
             <li><%= link_to 'Log Out', session_path, method: :delete %></li>
           </ul>
         </div><!--/.nav-collapse -->
       </div><!--/.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lol</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">

  </head>

  <body>

    <%= render 'admin/shared/menu' unless @disable_nav %>

    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <%= yield %>
  </body>
</html>